//
// FKTextFieldResults.swift
//
// Formatting and validation results.
//

import Foundation

/// Result generated by formatter pipeline.
public struct FKTextFieldFormattingResult: Equatable, Sendable {
  /// Sanitized text without grouping separators.
  public let rawText: String
  /// Display text shown in UI.
  public let formattedText: String
  /// Indicates whether content was truncated by max length.
  public let isTruncated: Bool
  /// Indicates whether illegal characters were removed.
  public let removedIllegalCharacters: Bool

  /// Creates a formatting result.
  public init(
    rawText: String,
    formattedText: String,
    isTruncated: Bool,
    removedIllegalCharacters: Bool
  ) {
    self.rawText = rawText
    self.formattedText = formattedText
    self.isTruncated = isTruncated
    self.removedIllegalCharacters = removedIllegalCharacters
  }
}

/// Result generated by validator pipeline.
public struct FKTextFieldValidationResult: Equatable, Sendable {
  /// Validation status.
  public let isValid: Bool
  /// Optional error message for invalid content.
  public let message: String?

  /// Creates a validation result.
  public init(isValid: Bool, message: String? = nil) {
    self.isValid = isValid
    self.message = message
  }

  /// Successful validation result.
  public static var valid: FKTextFieldValidationResult {
    FKTextFieldValidationResult(isValid: true)
  }
}

